apiVersion: v1
kind: Service
metadata:
  name: {{ include "fibos-node.fullname" . }}
  labels:
    {{- include "fibos-node.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.httpPort }}
      targetPort: 8888
      protocol: TCP
      name: http
    - port: {{ .Values.service.p2pPort }}
      targetPort: 9977
      nodePort: {{ .Values.service.p2pPort }}
      protocol: TCP
      name: p2p
  selector:
    {{- include "fibos-node.selectorLabels" . | nindent 4 }}
