apiVersion: v1
kind: Service
metadata:
  name: {{ include "enu-node.fullname" . }}
  labels:
    {{- include "enu-node.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.httpPort }}
      targetPort: 8123
      protocol: TCP
      name: http
    {{ if .Values.service.p2pPort }}
    - port: {{ .Values.service.p2pPort }}
      targetPort: 9003
      nodePort: {{ .Values.service.p2pPort }}
      protocol: TCP
      name: p2p
    {{- end }}
  selector:
    {{- include "enu-node.selectorLabels" . | nindent 4 }}
